### ISSUE TITLE
Frame resolution

### ISSUE THREAD

**Issue by silverhorse3** [circuitrocks/ESP32-RTSP#7]
I can see that it streams at 800x600, is there any way to reduce that resolution? That would help to make it faster

**Comment by beegee-tokyo** [comment]
Image size is set in the config file. You can experiment to change it in the Micro-RTSP library in [OV2640.cpp](https://github.com/circuitrocks/ESP32-RTSP/blob/16e826e33a00661cd89eff55f53d37121ee8999d/lib/Micro-RTSP/src/OV2640.cpp#L34)
You can try the different options.
But if I remember correct `FRAMESIZE_SVGA` was the only one that worked. Not sure, it is a long time since I worked on this code.

**Comment by silverhorse3** [comment]
Yes, i tried to change the resolution, but it always works at 800x600

**Comment by beegee-tokyo** [comment]
I am just using the Micro-RTSP library. Maybe raising an issue at their repository [Micro-RTSP](https://github.com/geeksville/Micro-RTSP) can give you an answer. I am not familiar with the internals of this library.
